modLoader="javafml"
loaderVersion="[43,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/SimplyHarvesting/issues"

[[mods]]
modId="simplyharvesting"
version="${file.jarVersion}"
displayName="Simply Harvesting"
displayTest="IGNORE_ALL_VERSION"
updateJSONURL="https://assets.melanx.de/updates/simply-harvesting.json"
authors="MelanX"
description="""
Right click to harvest any crop
"""

[[dependencies.simplyharvesting]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplyharvesting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    ordering="NONE"
    side="BOTH"
