modLoader="javafml"
loaderVersion="[45,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/SimplyHarvesting/issues"

[[mods]]
modId="simplyharvesting"
version="${file.jarVersion}"
displayName="Simply Harvesting"
displayTest="IGNORE_ALL_VERSION"
updateJSONURL="https://assets.melanx.de/updates/simply-harvesting.json"
authors="MelanX"
description="""
Right click to harvest any crop
"""

[[dependencies.simplyharvesting]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplyharvesting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4, 1.20)"
    ordering="NONE"
    side="BOTH"
