modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod.license}"
issueTrackerURL = "${mod.issue_url}"

[[mods]]
modId = "${mod.modid}"
version = "${mod.version}"
displayURL = "${mod.source_url}"
displayName = "Simply Harvesting"
updateJSONURL = "https://assets.melanx.de/updates/simply-harvesting.json"
authors = "MelanX"
description = """
Right click to harvest any crop
"""

[[dependencies.${ mod.modid }]]
   modId = "neoforge"
   type = "required"
   versionRange = "[${mod.neoforge},)"
   ordering = "NONE"
   side = "BOTH"

[[dependencies.${ mod.modid }]]
   modId = "minecraft"
   type = "required"
   versionRange = "[${mod.minecraft},)"
   ordering = "NONE"
   side = "BOTH"
