modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/ChaoticTrials/SimplyHarvesting/issues"

[[mods]]
modId="${modid}"
version="${mod_version}"
displayName="Simply Harvesting"
updateJSONURL="https://assets.melanx.de/updates/simply-harvesting.json"
displayURL="https://modrinth.com/user/MelanX"
authors="MelanX"
description="""
Right click to harvest any crop
"""

[[dependencies.${modid}]]
   modId = "neoforge"
   type = "required"
   versionRange = "[${neo_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${modid}]]
   modId="minecraft"
   type="required"
   versionRange="[${minecraft_version},)"
   ordering="NONE"
   side="BOTH"
